---
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_distribution: "{{ ansible_distribution | lower }}"
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ docker_apt_distribution }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key_url: "https://download.docker.com/linux/{{ docker_apt_distribution }}/gpg"
