---
- name: Get a list of all running containers
  tags:
    - stop
    - docker_containers_stop
  docker_host_info:
    containers: true
  register: docker_info

- name: Stop all running containers
  tags:
    - stop
    - docker_containers_stop
  docker_container:
    name: '{{ item.Names[0] | regex_replace("^/", "") }}'
    state: stopped
  loop: '{{ docker_info.containers }}'
