---
- name: Create and start Nginx container
  tags:
    - nginx
    - docker_container
    - service
  docker_container:
    name: "{{ application_name }}_nginx"
    image: "{{ nginx_image }}"
    hostname: nginx
    state: started
    ports:
      - 80:80
    command: "wait-for {{ django_network_alias }}:{{ django_network_port }} -- nginx -g 'daemon off;'"
    mounts:
      - source: "{{ nginx_static_volume }}"
        target: /static
      - source: "{{ nginx_media_volume }}"
        target: /media
    networks_cli_compatible: true
    networks:
      - name: "{{ application_network_name }}"
        aliases:
          - "{{ nginx_network_alias }}"
    healthcheck:
      test: wget -qO- http://localhost/healthcheck
